name: todo_ulist
description: "project developed for technical testing by ulist."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  cloud_firestore: ^4.14.0
  equatable: ^2.0.5
  firebase_core: ^2.24.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_modular: ^6.3.2
  mocktail: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
