// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfTCGN_yj9rwDbcnyjRaZPSN-kmshNESs',
    appId: '1:424550777791:web:98199d9a909c609653970a',
    messagingSenderId: '424550777791',
    projectId: 'todo-ulist',
    authDomain: 'todo-ulist.firebaseapp.com',
    storageBucket: 'todo-ulist.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZYiSDovNbi8zvGcniP1VE9h44Y1FDnqk',
    appId: '1:424550777791:android:d14d9c623e68429e53970a',
    messagingSenderId: '424550777791',
    projectId: 'todo-ulist',
    storageBucket: 'todo-ulist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQj2EFfmD92Ewyn8-Y0-gpNt2FsMUnCCQ',
    appId: '1:424550777791:ios:c31b076593937a8a53970a',
    messagingSenderId: '424550777791',
    projectId: 'todo-ulist',
    storageBucket: 'todo-ulist.appspot.com',
    iosBundleId: 'com.example.todoUlist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQj2EFfmD92Ewyn8-Y0-gpNt2FsMUnCCQ',
    appId: '1:424550777791:ios:da3c82bbcd7dd0a353970a',
    messagingSenderId: '424550777791',
    projectId: 'todo-ulist',
    storageBucket: 'todo-ulist.appspot.com',
    iosBundleId: 'com.example.todoUlist.RunnerTests',
  );
}
